### ISSUE TITLE
Empty POST response?

### ISSUE THREAD

**Issue by smpetrey** [zaichaopan/laravel-react-spa#3]
Hey there! I'm a bit new to Laravel and sculpting REST APIs (so thanks for bearing with me on this issue) but for some reason, when making POST requests to the `/api/register` endpoint in Postman — I'm getting an empty response and nothing is getting created in the database? 

<img width="883" alt="Screen Shot 2019-05-18 at 8 51 40 PM" src="https://user-images.githubusercontent.com/6411509/57976476-4e375e80-79af-11e9-9128-eb50a3b3a7d3.png">

The front-end works great and as expected out of the box (which is awesome I should add!), but I'm so curious why Postman isn't allowing requests and records to be saved. FWIW making POST requests to `/api/signin` works fine but man, I'm really struggling to understand why the Register API endpoint isn't working as expected in Postman. Cheers!

**Comment by zaichaopan** [comment]
Hi,
You forgot to include field "password_confirmation" when registering a new user. 

<img width="1074" alt="Screen Shot 2019-05-18 at 9 39 04 PM" src="https://user-images.githubusercontent.com/16104572/57977885-8a21f200-79b6-11e9-910b-c01b81546683.png">

**Comment by smpetrey** [comment]
Wow, that makes so much sense. I completely overlooked the confirmation field. Thanks @zaichaopan!
