### ISSUE TITLE
Auth routes always redirect to login > home when accessed via url

### ISSUE THREAD

**Issue by wayne-thorley** [zaichaopan/laravel-react-spa#7]
Whenever you access auth routes directly (type /profile/1 into the url bar) I always get redirected first to the login page and then to the home page.

Seems to be related to the async nature of the authenticated variable in auth-route.js.
When I alert(authenticated) it initially returns false which triggers the <Redirect to={{ pathname: '/login' on line 33

Is there any way of awaiting the authenticated check prior to the return statement on line 23 of auth-route.js?
I can't get my head around how to do this.

**Comment by zaichaopan** [comment]
Hi @wayne-thorley thanks for pointing out the issue. There is a bug in the code: should set current user before setting Initializing. I made a commit to fix it. Please give it a try. Thanks

**Comment by wayne-thorley** [comment]
Legend. Works perfectly, thank you 🙌
